languages:
  Ruby: true
  JavaScript: true
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - Gemfile.lock
exclude_paths:
- "features/step_definitions"
- "features/support"
- "db/schema.rb"
- "db/seeds.rb"
- "db/fixtures/**/*"
- ".rubocop"
