web:
  build: .
  command: develop
  volumes:
    - .:/fti
  ports:
    - '3000:3000'
  links:
    - postgres
  env_file: dev.env

postgres:
  image: postgres
  container_name: postgres_fti

redis:
  image: redis
  container_name: redis_fti
